version: '3.8'

services:
  whatsapp-monitor:
    build: .
    container_name: whatsapp-monitor
    ports:
      - "3000:3000"
    volumes:
      - ./auth_info:/app/auth_info
      - ./whatsapp_data.db:/app/whatsapp_data.db
      - ./logs:/app/logs
    environment:
      - PORT=3000
      - WEBHOOK_URL=${WEBHOOK_URL:-}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/stats"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  auth_data:
  db_data: